# Generated by Django 4.1.5 on 2023-02-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_remove_aboutus_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(null=True, upload_to='aboutus/'),
        ),
    ]
